# Generated by Django 5.1 on 2026-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20260511_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feedback_open',
            field=models.BooleanField(default=False),
        ),
    ]
