# Generated by Django 5.1 on 2026-05-29 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='pollresponse',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'option_text')},
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('poll', 'session_id')},
        ),
    ]
